import Image from "next/image";
import React from "react";
import img1 from "@/public/images/1.png";
import img2 from "@/public/images/2.png";
import img3 from "@/public/images/3.png";
import img4 from "@/public/images/4.png";
import img5 from "@/public/images/5.png";
import img6 from "@/public/images/6.png";
import img7 from "@/public/images/7.png";

const Popular = () => {
  return (
    <div className="text-white container mx-auto px-5 flex flex-col items-center gap-5">
      <div className="text-[30px] md:text-[48px] md:leading-[30px] leading-[35px] text-center ">
        Popular NFTs generated by Artists
      </div>
      <p className="text-center font-inter my-5">
        3dotlinks AI integration is a game-changer in the NFT art world. It
        offers a powerful canvas for artists to redefine art creation and{" "}
        <br className="hidden lg:block" />
        innovation while preserving cultural art in an entirely new format. With
        this platform, the convergence of human ingenuity and AI{" "}
        <br className="hidden lg:block" /> technology is set to redefine the
        boundaries of artistic expression and creative possibilities, ushering
        in a digital art renaissance.
      </p>
      {/* cards grid */}
      <div className="grid grid-row-height gap-7 w-full grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
        <div className="text-white sm:h-[377px] sm:col-span-2 md:col-span-3 lg:col-span-1 lg:row-span-1 lg:h-[377px] lg:max-h-[377px]">
          <Image
            className="object-cover block h-full w-full"
            src={img1}
            alt="img_1"
          />
        </div>
        <div className="text-white md:max-w-[377] sm:row-span-2 sm:col-span-2">
          <Image
            className="object-cover block h-full w-full"
            src={img2}
            alt="img_1"
          />
        </div>
        <div className="text-white sm:h-[377px] sm:max-w-[377px]">
          <Image
            className="object-cover block h-full w-full"
            src={img3}
            alt="img_1"
          />
        </div>
        <div className="text-white sm:max-w-[377px] sm:row-span-2 lg:row-span-2">
          <Image
            className="object-cover block h-full w-full"
            src={img4}
            alt="img_1"
          />
        </div>
        <div className="text-white sm:h-[377px] sm:max-w-[377px]">
          <Image
            className="object-cover block h-full w-full"
            src={img5}
            alt="img_1"
          />
        </div>
        <div className="text-white sm:h-[377px] sm:max-w-[377px]">
          <Image
            className="object-cover block h-full w-full"
            src={img6}
            alt="img_1"
          />
        </div>
        <div className="text-white sm:h-[377px] sm:col-span-1 md:col-span-3 lg:col-span-2">
          <Image
            className="object-cover block h-full w-full"
            src={img7}
            alt="img_1"
          />
        </div>
      </div>
    </div>
  );
};

export default Popular;
