import type { Metadata } from "next";
import { Inter, Zen_Dots } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const zen_dots = Zen_Dots({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Task | OctaLoop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${zen_dots.className} overflow-x-hidden`}>
        {children}
      </body>
    </html>
  );
}
